# XsensMti Calibration parameter
#-------------Accelerometer-------
accel_misalignment: [1, -0.000745693,   0.00211438,
           0,            1,  -0.00214681,
          -0,            0,            1]

accel_scale: [1.00113,       0,       0,
      0, 1.00177,       0,
      0,       0, 1.00095]

accel_bias: [0.0109207,
-0.0158071,
-0.0366243]

##-------------Gyroscope---------
gyro_misalignment: [1,   -0.31711,  -0.119093,
-0.0199497,          1, -0.0462595,
  -0.70299,  -0.146101,          1]

gyro_scale: [0.715057,        0,        0,
       0,  0.88019,        0,
       0,        0, 0.947628]

gyro_bias: [-0.0161674,
-0.0219267,
-0.0157881]
#------------------------------------------------------------------
#------------------------------------------------------------------